const fs = require('fs');

let content = fs.readFileSync('pathora/frontend/src/features/dashboard/components/PrivateTourInstanceDetailPage.tsx', 'utf8');

// 1. Spacing & layout -> `py-8 md:py-10 px-4 md:px-6 lg:px-8 max-w-7xl mx-auto`
content = content.replace(/max-w-5xl/g, 'max-w-7xl');
content = content.replace(/p-6 md:p-8/g, 'py-8 md:py-10 px-4 md:px-6 lg:px-8');

// 2. Affordances and structural cleanup for utility stacking
content = content.replace(/flex flex-col md:flex-row/g, 'v-stack md:h-stack');
content = content.replace(/flex items-center justify-between/g, 'h-stack items-center justify-between');
content = content.replace(/flex flex-wrap items-center/g, 'h-stack flex-wrap items-center');
content = content.replace(/flex flex-wrap/g, 'h-stack flex-wrap');
content = content.replace(/flex items-center/g, 'h-stack items-center');
content = content.replace(/flex flex-col/g, 'v-stack');
content = content.replace(/flex-1/g, 'spacer');

// 3. Typogaphy updates to slate and the Pathora bold display
content = content.replace(/text-stone-/g, 'text-slate-');
content = content.replace(/bg-stone-/g, 'bg-slate-');
content = content.replace(/border-stone-/g, 'border-slate-');
content = content.replace(/text-2xl md:text-3xl font-bold tracking-tight/g, 'text-3xl md:text-4xl font-bold tracking-tighter');
content = content.replace(/text-xl font-bold tracking-tight/g, 'text-2xl font-bold tracking-tight');

// Fix inline-h-stack generated by bad replacer earlier
content = content.replace(/inline-h-stack items-center/g, 'inline-flex items-center');

// 4. Panel shapes and styling
content = content.replace(/rounded-2xl/g, 'rounded-[1.5rem]');
// Shadows and specific styling
content = content.replace(/shadow-sm/g, 'shadow-[0_20px_40px_-15px_rgba(0,0,0,0.05)]');
content = content.replace(/bg-amber-50\/50 border border-amber-100/g, 'bg-amber-50 border border-amber-100');

// Fix buttons to not use slate where an accent is better
content = content.replace(/bg-slate-900 text-white/g, 'bg-slate-900 text-white');

fs.writeFileSync('pathora/frontend/src/features/dashboard/components/PrivateTourInstanceDetailPage.tsx', content);
