//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by scripts/generate-auth-roles.ts
//     DO NOT EDIT MANUALLY. Edit role.json and re-run the generator.
//     Generated: 2026-04-08T11:43:22.854Z
// </auto-generated>
//------------------------------------------------------------------------------

/**
 * Role names exported from role.json.
 * These are used by middleware.ts for server-side routing authorization.
 * Single source of truth: role.json
 */

const ADMIN_ROLE_NAMES = new Set<string>(["Admin"]);
const MANAGER_ROLE_NAMES = new Set<string>(["Manager"]);
const HOTELSERVICEPROVIDER_ROLE_NAMES = new Set<string>(["HotelServiceProvider"]);
const TRANSPORTPROVIDER_ROLE_NAMES = new Set<string>(["TransportProvider"]);
const TOUROPERATOR_ROLE_NAMES = new Set<string>(["TourOperator"]);
const TOURGUIDE_ROLE_NAMES = new Set<string>(["TourGuide"]);

// All role names from role.json
const ALL_ROLE_NAMES: string[] = ["Admin", "Manager", "TourOperator", "TourGuide", "Customer", "TransportProvider", "HotelServiceProvider"];

export { ADMIN_ROLE_NAMES, MANAGER_ROLE_NAMES, HOTELSERVICEPROVIDER_ROLE_NAMES, TRANSPORTPROVIDER_ROLE_NAMES, TOUROPERATOR_ROLE_NAMES, TOURGUIDE_ROLE_NAMES, ALL_ROLE_NAMES };
