using System.Text.Json.Serialization;

namespace Application.Dtos;

public sealed record TourInstanceDto(
    [property: JsonPropertyName("id")] Guid Id,
    [property: JsonPropertyName("tourId")] Guid TourId,
    [property: JsonPropertyName("tourInstanceCode")] string TourInstanceCode,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("tourName")] string TourName,
    [property: JsonPropertyName("tourCode")] string TourCode,
    [property: JsonPropertyName("classificationId")] Guid ClassificationId,
    [property: JsonPropertyName("classificationName")] string ClassificationName,
    [property: JsonPropertyName("location")] string? Location,
    [property: JsonPropertyName("thumbnail")] ImageDto? Thumbnail,
    [property: JsonPropertyName("images")] List<ImageDto> Images,
    [property: JsonPropertyName("startDate")] DateTimeOffset StartDate,
    [property: JsonPropertyName("endDate")] DateTimeOffset EndDate,
    [property: JsonPropertyName("durationDays")] int DurationDays,
    [property: JsonPropertyName("currentParticipation")] int CurrentParticipation,
    [property: JsonPropertyName("maxParticipation")] int MaxParticipation,
    [property: JsonPropertyName("basePrice")] decimal BasePrice,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("instanceType")] string InstanceType,
    [property: JsonPropertyName("cancellationReason")] string? CancellationReason,
    [property: JsonPropertyName("rating")] decimal Rating,
    [property: JsonPropertyName("totalBookings")] int TotalBookings,
    [property: JsonPropertyName("revenue")] decimal Revenue,
    [property: JsonPropertyName("confirmationDeadline")] DateTimeOffset? ConfirmationDeadline,
    [property: JsonPropertyName("managers")] List<TourInstanceManagerDto> Managers,
    [property: JsonPropertyName("includedServices")] List<string> IncludedServices,
    [property: JsonPropertyName("pricingPolicy")] PricingPolicyDto? PricingPolicy = null,
    [property: JsonPropertyName("cancellationPolicy")] CancellationPolicyDto? CancellationPolicy = null,
    [property: JsonPropertyName("depositPolicy")] DepositPolicyDto? DepositPolicy = null,
    /// <summary>Giá chốt sau co-design (private tour); null khi chưa set.</summary>
    [property: JsonPropertyName("finalSellPrice")] decimal? FinalSellPrice = null,
    [property: JsonPropertyName("wantsCustomization")] bool WantsCustomization = false,
    [property: JsonPropertyName("customizationNotes")] string? CustomizationNotes = null,
    [property: JsonPropertyName("managerReviewNote")] string? ManagerReviewNote = null,
    [property: JsonPropertyName("days")] List<TourInstanceDayDto>? Days = null);
