/**
 * Generates auth-roles.ts from role.json seed data.
 * Single source of truth: role.json
 *
 * Usage:
 *   npx tsx scripts/generate-auth-roles.ts
 *
 * This script reads role names from the backend role.json and generates
 * auth-roles.ts in the frontend src directory.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Resolve role.json relative to the workspace root (two levels up from pathora/)
const workspaceRoot = join(__dirname, '..', '..');
const roleJsonPath = join(
  workspaceRoot,
  'panthora_be',
  'src',
  'Infrastructure',
  'Data',
  'Seed',
  'Seeddata',
  'role.json'
);

// Output path relative to workspace root
const outputPath = join(
  workspaceRoot,
  'pathora',
  'frontend',
  'src',
  'auth-roles.ts'
);

interface Role {
  Id: number;
  Name: string;
  Type: number;
}

function generate(): void {
  const jsonContent = readFileSync(roleJsonPath, 'utf-8');
  const roles: Role[] = JSON.parse(jsonContent);

  if (!roles || roles.length === 0) {
    throw new Error('No roles found in role.json');
  }

  const sortedRoles = roles.sort((a, b) => a.Id - b.Id);

  const adminRoles = sortedRoles
    .filter((r) => r.Name === 'Admin')
    .map((r) => `"${r.Name}"`);

  const managerRoles = sortedRoles
    .filter((r) => r.Name === 'Manager')
    .map((r) => `"${r.Name}"`);

  const hotelServiceProviderRoles = sortedRoles
    .filter((r) => r.Name === 'HotelServiceProvider')
    .map((r) => `"${r.Name}"`);

  const allRoleNames = sortedRoles.map((r) => `"${r.Name}"`);

  const generatedDate = new Date().toISOString();

  const output = `//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by scripts/generate-auth-roles.ts
//     DO NOT EDIT MANUALLY. Edit role.json and re-run the generator.
//     Generated: ${generatedDate}
// </auto-generated>
//------------------------------------------------------------------------------

/**
 * Role names exported from role.json.
 * These are used by middleware.ts for server-side routing authorization.
 * Single source of truth: role.json
 */

const ADMIN_ROLE_NAMES = new Set<string>([${adminRoles.join(', ')}]);
const MANAGER_ROLE_NAMES = new Set<string>([${managerRoles.join(', ')}]);
const HOTELSERVICEPROVIDER_ROLE_NAMES = new Set<string>([${hotelServiceProviderRoles.join(', ')}]);

// All role names from role.json
const ALL_ROLE_NAMES: string[] = [${allRoleNames.join(', ')}];

export { ADMIN_ROLE_NAMES, MANAGER_ROLE_NAMES, HOTELSERVICEPROVIDER_ROLE_NAMES, ALL_ROLE_NAMES };
`;

  const outputDir = dirname(outputPath);
  mkdirSync(outputDir, { recursive: true });

  writeFileSync(outputPath, output, 'utf-8');

  console.log(`Generated: ${outputPath}`);
  console.log(`  Roles found: ${sortedRoles.length}`);
  console.log(`  Admin roles: ${[...adminRoles]}`);
  console.log(`  Manager roles: ${[...managerRoles]}`);
  console.log(`  HotelServiceProvider roles: ${[...hotelServiceProviderRoles]}`);
}

generate();
