export { default as HeroSection } from "./HeroSection";
export { default as LatestToursSection } from "./LatestToursSection";
export { default as FeaturedTripsSection } from "./FeaturedTripsSection";
export { default as StatsSection } from "./StatsSection";
export { default as TrendingDestinationsSection } from "./DestinationsSection";
export { default as ReviewsSection } from "./ReviewsSection";
export { CTASection, WhyChooseSection } from "./BottomSections";

export { BoldNavbar } from "./BoldNavbar";
export { BoldHeroSection } from "./BoldHeroSection";
export { BoldStatsStrip } from "./BoldStatsStrip";
export { BoldTrendingDestinations } from "./BoldTrendingDestinations";
export { BoldVideoShowcase } from "./BoldVideoShowcase";
export { BoldFeaturedTrips } from "./BoldFeaturedTrips";
export { BoldLatestTours } from "./BoldLatestTours";
export { BoldWhyChooseUs } from "./BoldWhyChooseUs";
export { BoldCtaSection } from "./BoldCtaSection";
export { BoldReviewsSection } from "./BoldReviewsSection";
export { BoldFooter } from "./BoldFooter";
export { BoldTiltCard } from "./BoldTiltCard";
