#Requires -Version 5.1
<#
.SYNOPSIS
    Generates RoleConstants.cs from role.json seed data.
    Single source of truth: role.json

.DESCRIPTION
    Reads role names from Infrastructure/Data/Seed/Seeddata/role.json
    and generates Application/Common/Constant/RoleConstants.cs.
    Must be run from the panthora_be directory or a subdirectory.

.PARAMETER OutputPath
    Override the output path for RoleConstants.cs.
    Defaults to the standard location relative to script directory.

.EXAMPLE
    .\scripts\GenerateRoleConstants.ps1
    Generate RoleConstants.cs in default location.
#>

param(
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

# Resolve paths
$ScriptDir = $PSScriptRoot
if ([string]::IsNullOrEmpty($ScriptDir)) {
    $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$RepoRoot = $ScriptDir
# Walk up to find repository root (where LocalService.slnx is)
while ($null -ne $RepoRoot -and $RepoRoot -ne (Split-Path -Parent $RepoRoot)) {
    if (Test-Path (Join-Path $RepoRoot "LocalService.slnx")) {
        break
    }
    $RepoRoot = Split-Path -Parent $RepoRoot
}

if ([string]::IsNullOrEmpty($RepoRoot) -or -not (Test-Path (Join-Path $RepoRoot "LocalService.slnx"))) {
    Write-Error "Could not find repository root (LocalService.slnx not found). Run this script from within panthora_be/."
    exit 1
}

$RoleJsonPath = Join-Path $RepoRoot "src\Infrastructure\Data\Seed\Seeddata\role.json"
if (-not (Test-Path $RoleJsonPath)) {
    Write-Error "role.json not found at: $RoleJsonPath"
    exit 1
}

$DefaultOutputPath = Join-Path $RepoRoot "src\Application\Common\Constant\RoleConstants.cs"
$OutFile = if ($OutputPath) { $OutputPath } else { $DefaultOutputPath }

# Read and parse role.json
$JsonContent = Get-Content -Path $RoleJsonPath -Raw -Encoding UTF8
$Roles = $JsonContent | ConvertFrom-Json

if ($null -eq $Roles -or $Roles.Count -eq 0) {
    Write-Error "No roles found in role.json"
    exit 1
}

# Sort roles by Id for deterministic output
$SortedRoles = $Roles | Sort-Object { $_.Id }

# Build individual constants
$IndividualConstants = @()
foreach ($role in $SortedRoles) {
    $name = $role.Name
    $PascalName = ($name -split '_' | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }) -join ''
    $IndividualConstants += "    public const string $PascalName = `"$name`";"
}

# Build combined-role constants (Admin + each other role)
$OtherRoles = $SortedRoles | Where-Object { $_.Name -ne 'Admin' }
$CombinedConstants = @()
$CombinedConstants += "    // Combined role constants"

foreach ($other in $OtherRoles) {
    $otherPascal = ($other.Name -split '_' | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }) -join ''
    $CombinedConstants += "    public const string Admin_$otherPascal = `"Admin,$($other.Name)`";"
}

# Admin + Manager + TourDesigner
$TourDesignerRole = $SortedRoles | Where-Object { $_.Name -eq 'TourDesigner' }
if ($null -ne $TourDesignerRole) {
    $CombinedConstants += "    public const string Admin_Manager_TourDesigner = `"Admin,Manager,TourDesigner`";"
}

# Admin + Manager + TourGuide
$TourGuideRole = $SortedRoles | Where-Object { $_.Name -eq 'TourGuide' }
if ($null -ne $TourGuideRole) {
    $CombinedConstants += "    public const string Admin_Manager_TourGuide = `"Admin,Manager,TourGuide`";"
}

# Generate C# file
$GeneratedDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$Header = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by scripts/GenerateRoleConstants.ps1
//     DO NOT EDIT MANUALLY. Edit role.json and re-run the generator.
//     Generated: $GeneratedDate
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Constant;

public static class RoleConstants
{
$($IndividualConstants -join "`n")

$($CombinedConstants -join "`n")
}
"@

# Ensure output directory exists
$OutDir = Split-Path -Parent $OutFile
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}

# Write output
$Header | Set-Content -Path $OutFile -Encoding UTF8 -NoNewline
Write-Host "Generated: $OutFile" -ForegroundColor Green
Write-Host "  Roles found: $($SortedRoles.Count)"
Write-Host "  Individual constants: $($IndividualConstants.Count)"
Write-Host "  Combined constants: $($CombinedConstants.Count)"
